### ISSUE TITLE
Routes without prefix?

### ISSUE THREAD

**Issue by jalehman** [gf3/secretary#22]
The readme mentions that "If the browser you're targeting does not support HTML5 history you can call `(secretary/set-config! :prefix "#")` to prefix generated URIs with a "#"." 

It seems that should a call to `set-config!` be omitted, the `:prefix` will be set to an empty string. That leads me to believe that generated routes would have no kind of prefix in the url -- yet all of mine do by default.

Is the `#` prefix supposed to always be present by default, or is there a way to disable it?

**Comment by city41** [comment]
@Rodeoclash 

I got secretary working with Html5History, here is a demo: https://gist.github.com/city41/aab464ae6c112acecfe1

**Comment by gf3** [comment]
@Rodeoclash @city41 wow i must have missed these messages over the break, so sorry! i'll try and whip up an example for you today

**Comment by koddo** [comment]
gf3, I've recently asked you to post a working example of routing without prefix. Have you seen this?
https://github.com/kibu-australia/pushy

This worked for me.

**Comment by koddo** [comment]
I'm sorry, it didn't work for me yet, it only handles history, I can't make it dispatch paths.

**Comment by koddo** [comment]
This is magic. Tried again, and it pushy worked.

**Comment by gf3** [comment]
@koddo glad you were able to get it working!
