### ISSUE TITLE
Redirecting to http://example.com/#/ from http://example.com/

### ISSUE THREAD

**Issue by Quantisan** [gf3/secretary#43]
I couldn't figure out how to do this properly. Right now http://example.com/ is blank because all my routes are set by secretary. Users need to use http://example.com/#/ for the app to load. Is there a way to set a root route? I'm thinking of redirecting `/` to `/#/` but I don't know how to do that aside from hardcoding it in the index.html which would break things. Any suggestion please?

**Comment by koddo** [comment]
@gf3, could you post a minimal working example that works without # prefix? This snippet does not help, links like <a href="/path">...</a> do not get dispatched by secretary and the browser gets 404.
