### ISSUE TITLE
Macro refer syntax changed in latest ClojureScript 

### ISSUE THREAD

**Issue by jeluard** [gf3/secretary#53]
Starting `2371` the proper way to refer a macro is:

```clojure
(ns app.routes
  (:require [secretary.core :as secretary :refer-macros [defroute]]))
```

The documentation should probably mention this change.

**Comment by ducky427** [comment]
Clojurescript v0.0-2755 has made this process even easier. See the post by @swannodette [here](https://groups.google.com/forum/#!topic/clojurescript/FoiqNV5nunQ).
