### ISSUE TITLE
Stupid question, but updating the URL?

### ISSUE THREAD

**Issue by Rodeoclash** [gf3/secretary#58]
Sorry if I've missed this in the docs somewhere, however:

I've got things setup nicely with my routes and reagent for rendering. The ```secretary/dispatch!``` works great for navigating around, and my HTML5 navigation on the server is correctly loading the application index and providing the correct paths to secretary on deep links when the page loads.

My question is, how can I update the location in the URL bar on dispatch? Is this something I should be looking into in the Google Closure docs or have I misconfigured secretary somehow?

**Comment by kernelp4nic** [comment]
You always can call javascript:

```

**Comment by Rodeoclash** [comment]
Got it, I wasn't sure if that was something secretary would handle or that I should implement myself. Thanks!
