### ISSUE TITLE
Accessing by URL does not trigger event in defroute

### ISSUE THREAD

**Issue by ryepesg** [gf3/secretary#59]
For example, when user clicks `<a href="#/users/jim">Jim</a>`, it will trigger 
**(defroute user-path "/users/:id" [id] ...)**. However, the event is not triggered when I directly type in a new window **index.html#/users/jim**.

In Emberjs, the state is associated with each URL, so bookmarks in the browser can reference the exact state which the user want to save.

**Comment by kernelp4nic** [comment]
You can listen to url hash changes like this:

```clojure
(set! (.-onhashchange js/window)
        (fn [e]
          (secretary/dispatch! (.-hash js/window.location)) false))
```

**Comment by ryepesg** [comment]
Thanks! It solves the problem, regards,
