### ISSUE TITLE
version 1.2.2 has public/index.html, public/out/* etc.....

### ISSUE THREAD

**Issue by twillis** [gf3/secretary#67]
I'm actually wondering if this was intentional or not because 1.2.1 only had secretary/* 

upgrading to it broke my app because my app serves the index.html dynamically from a template but I believe the ring.middleware.resource.wrap-resource is picking up the index.html from 1.2.2 instead of my handler. 

I could probably work around this, but I suspect, 1.2.2 was probably not supposed to be packaged with all the public/out/* stuff

**Comment by noprompt** [comment]
Yeah, that's definitely not what we want.

**Comment by noprompt** [comment]
@twillis There's a new version which makes sure there's nothing in `resources/public`.

**Comment by twillis** [comment]
much thanks sir.
