### ISSUE TITLE
any way to build isomorphic routes? 

### ISSUE THREAD

**Issue by jdkealy** [gf3/secretary#71]
Can i have a link that goes to "/about" instead of "/#about"? 
I have all other elements of an isomorphic app up and running except this part.

**Comment by jdkealy** [comment]
Actually, to be clear, I'm not so concerned with the server-side routing issue, but more just concerned with navigating to "/about" and having secretary catch the event.

**Comment by gf3** [comment]
@jdkealy yes this is possible via the HTML5 History API

**Comment by gf3** [comment]
@jdkealy good example here → https://gist.github.com/city41/aab464ae6c112acecfe1
