### ISSUE TITLE
Call a javascript function after loading a new page?

### ISSUE THREAD

**Issue by Quantisan** [gf3/secretary#78]
I'm using Foundation 5 for my CSS template and their javascript component asks for calling their JS function at the end of each page. Foundation is not seeing the new DOMs on routing so they aren't working. Is it possible to run a function after each page dispatch in secretary?

**Comment by noprompt** [comment]
@Quantisan Apologies for the delay on responding to this question. Can you provide a little bit more detail so I can try to make a suggestion?

**Comment by Quantisan** [comment]
I ended up using :component-did-mount lifecycle component in reagent.

**Comment by Quantisan** [comment]
thank you
