### ISSUE TITLE
defroute default-route overrides everything after it

### ISSUE THREAD

**Issue by vans163** [gf3/secretary#89]
Once you specify defroute default-route, any defroutes after it get ignored.

I thought default-route was special for this reason that it would not override things like this.

**Comment by RyanBertrand** [comment]
Do you mean a wildcard route?  
`(defroute "*" {:as params})`

If so, I always put this last in my list of defroutes as a catch all.  I believe they are tested in order.

**Comment by vans163** [comment]
I believe this is my mistake, I am new to clojurescript I thought the http://www.lispcast.com/mastering-client-side-routing-with-secretary-and-goog-history "defroute default-route" was special here.

**Comment by gf3** [comment]
indeed they are tested in order—you should place it at the end
